// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: packfile/packfile.proto

package packfile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackfileStatus int32

const (
	PackfileStatus_STAGED     PackfileStatus = 0
	PackfileStatus_COMMITTED  PackfileStatus = 1
	PackfileStatus_SUPERSEDED PackfileStatus = 2
	PackfileStatus_DELETED    PackfileStatus = 3
)

// Enum value maps for PackfileStatus.
var (
	PackfileStatus_name = map[int32]string{
		0: "STAGED",
		1: "COMMITTED",
		2: "SUPERSEDED",
		3: "DELETED",
	}
	PackfileStatus_value = map[string]int32{
		"STAGED":     0,
		"COMMITTED":  1,
		"SUPERSEDED": 2,
		"DELETED":    3,
	}
)

func (x PackfileStatus) Enum() *PackfileStatus {
	p := new(PackfileStatus)
	*p = x
	return p
}

func (x PackfileStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackfileStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_packfile_packfile_proto_enumTypes[0].Descriptor()
}

func (PackfileStatus) Type() protoreflect.EnumType {
	return &file_packfile_packfile_proto_enumTypes[0]
}

func (x PackfileStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackfileStatus.Descriptor instead.
func (PackfileStatus) EnumDescriptor() ([]byte, []int) {
	return file_packfile_packfile_proto_rawDescGZIP(), []int{0}
}

type PackfileClassification int32

const (
	PackfileClassification_SECOND_CLASS PackfileClassification = 0
	PackfileClassification_FIRST_CLASS  PackfileClassification = 1
)

// Enum value maps for PackfileClassification.
var (
	PackfileClassification_name = map[int32]string{
		0: "SECOND_CLASS",
		1: "FIRST_CLASS",
	}
	PackfileClassification_value = map[string]int32{
		"SECOND_CLASS": 0,
		"FIRST_CLASS":  1,
	}
)

func (x PackfileClassification) Enum() *PackfileClassification {
	p := new(PackfileClassification)
	*p = x
	return p
}

func (x PackfileClassification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackfileClassification) Descriptor() protoreflect.EnumDescriptor {
	return file_packfile_packfile_proto_enumTypes[1].Descriptor()
}

func (PackfileClassification) Type() protoreflect.EnumType {
	return &file_packfile_packfile_proto_enumTypes[1]
}

func (x PackfileClassification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackfileClassification.Descriptor instead.
func (PackfileClassification) EnumDescriptor() ([]byte, []int) {
	return file_packfile_packfile_proto_rawDescGZIP(), []int{1}
}

type PackfileMetadata struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PackfileId           string                 `protobuf:"bytes,1,opt,name=packfile_id,json=packfileId,proto3" json:"packfile_id,omitempty"`
	Status               PackfileStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=packfile.PackfileStatus" json:"status,omitempty"`
	Classification       PackfileClassification `protobuf:"varint,3,opt,name=classification,proto3,enum=packfile.PackfileClassification" json:"classification,omitempty"`
	RepositoryId         string                 `protobuf:"bytes,4,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	StorageNamespace     string                 `protobuf:"bytes,5,opt,name=storage_namespace,json=storageNamespace,proto3" json:"storage_namespace,omitempty"`
	ObjectCount          int64                  `protobuf:"varint,6,opt,name=object_count,json=objectCount,proto3" json:"object_count,omitempty"`
	SizeBytes            int64                  `protobuf:"varint,7,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	SizeBytesCompressed  int64                  `protobuf:"varint,8,opt,name=size_bytes_compressed,json=sizeBytesCompressed,proto3" json:"size_bytes_compressed,omitempty"`
	CompressionAlgorithm string                 `protobuf:"bytes,9,opt,name=compression_algorithm,json=compressionAlgorithm,proto3" json:"compression_algorithm,omitempty"`
	ChecksumAlgorithm    string                 `protobuf:"bytes,10,opt,name=checksum_algorithm,json=checksumAlgorithm,proto3" json:"checksum_algorithm,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	SourcePackfileIds    []string               `protobuf:"bytes,12,rep,name=source_packfile_ids,json=sourcePackfileIds,proto3" json:"source_packfile_ids,omitempty"`
	// IndexPath is the path to the SSTable index file for O(1) content hash lookups.
	// Empty string means no index is available.
	IndexPath            string                 `protobuf:"bytes,13,opt,name=index_path,json=indexPath,proto3" json:"index_path,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PackfileMetadata) Reset() {
	*x = PackfileMetadata{}
	mi := &file_packfile_packfile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackfileMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackfileMetadata) ProtoMessage() {}

func (x *PackfileMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_packfile_packfile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackfileMetadata.ProtoReflect.Descriptor instead.
func (*PackfileMetadata) Descriptor() ([]byte, []int) {
	return file_packfile_packfile_proto_rawDescGZIP(), []int{0}
}

func (x *PackfileMetadata) GetPackfileId() string {
	if x != nil {
		return x.PackfileId
	}
	return ""
}

func (x *PackfileMetadata) GetStatus() PackfileStatus {
	if x != nil {
		return x.Status
	}
	return PackfileStatus_STAGED
}

func (x *PackfileMetadata) GetClassification() PackfileClassification {
	if x != nil {
		return x.Classification
	}
	return PackfileClassification_SECOND_CLASS
}

func (x *PackfileMetadata) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *PackfileMetadata) GetStorageNamespace() string {
	if x != nil {
		return x.StorageNamespace
	}
	return ""
}

func (x *PackfileMetadata) GetObjectCount() int64 {
	if x != nil {
		return x.ObjectCount
	}
	return 0
}

func (x *PackfileMetadata) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *PackfileMetadata) GetSizeBytesCompressed() int64 {
	if x != nil {
		return x.SizeBytesCompressed
	}
	return 0
}

func (x *PackfileMetadata) GetCompressionAlgorithm() string {
	if x != nil {
		return x.CompressionAlgorithm
	}
	return ""
}

func (x *PackfileMetadata) GetChecksumAlgorithm() string {
	if x != nil {
		return x.ChecksumAlgorithm
	}
	return ""
}

func (x *PackfileMetadata) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PackfileMetadata) GetSourcePackfileIds() []string {
	if x != nil {
		return x.SourcePackfileIds
	}
	return nil
}

func (x *PackfileMetadata) GetIndexPath() string {
	if x != nil {
		return x.IndexPath
	}
	return ""
}

type PackfileSnapshot struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RepositoryId      string                 `protobuf:"bytes,1,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	ActivePackfileIds []string               `protobuf:"bytes,2,rep,name=active_packfile_ids,json=activePackfileIds,proto3" json:"active_packfile_ids,omitempty"`
	StagedPackfileIds []string               `protobuf:"bytes,3,rep,name=staged_packfile_ids,json=stagedPackfileIds,proto3" json:"staged_packfile_ids,omitempty"`
	LastCommitAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=last_commit_at,json=lastCommitAt,proto3" json:"last_commit_at,omitempty"`
	LastMergeAt       *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_merge_at,json=lastMergeAt,proto3" json:"last_merge_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PackfileSnapshot) Reset() {
	*x = PackfileSnapshot{}
	mi := &file_packfile_packfile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackfileSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackfileSnapshot) ProtoMessage() {}

func (x *PackfileSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_packfile_packfile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackfileSnapshot.ProtoReflect.Descriptor instead.
func (*PackfileSnapshot) Descriptor() ([]byte, []int) {
	return file_packfile_packfile_proto_rawDescGZIP(), []int{1}
}

func (x *PackfileSnapshot) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *PackfileSnapshot) GetActivePackfileIds() []string {
	if x != nil {
		return x.ActivePackfileIds
	}
	return nil
}

func (x *PackfileSnapshot) GetStagedPackfileIds() []string {
	if x != nil {
		return x.StagedPackfileIds
	}
	return nil
}

func (x *PackfileSnapshot) GetLastCommitAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastCommitAt
	}
	return nil
}

func (x *PackfileSnapshot) GetLastMergeAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastMergeAt
	}
	return nil
}

type UploadSession struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UploadId     string                 `protobuf:"bytes,1,opt,name=upload_id,json=uploadId,proto3" json:"upload_id,omitempty"`
	PackfileId   string                 `protobuf:"bytes,2,opt,name=packfile_id,json=packfileId,proto3" json:"packfile_id,omitempty"`
	RepositoryId string                 `protobuf:"bytes,3,opt,name=repository_id,json=repositoryId,proto3" json:"repository_id,omitempty"`
	TmpPath      string                 `protobuf:"bytes,4,opt,name=tmp_path,json=tmpPath,proto3" json:"tmp_path,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Packfile info from init request for validation at complete time
	ExpectedSize        int64  `protobuf:"varint,6,opt,name=expected_size,json=expectedSize,proto3" json:"expected_size,omitempty"`
	ExpectedChecksum    string `protobuf:"bytes,7,opt,name=expected_checksum,json=expectedChecksum,proto3" json:"expected_checksum,omitempty"`
	Compression         string `protobuf:"bytes,8,opt,name=compression,proto3" json:"compression,omitempty"`
	ExpectedObjectCount int64  `protobuf:"varint,9,opt,name=expected_object_count,json=expectedObjectCount,proto3" json:"expected_object_count,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UploadSession) Reset() {
	*x = UploadSession{}
	mi := &file_packfile_packfile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSession) ProtoMessage() {}

func (x *UploadSession) ProtoReflect() protoreflect.Message {
	mi := &file_packfile_packfile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSession.ProtoReflect.Descriptor instead.
func (*UploadSession) Descriptor() ([]byte, []int) {
	return file_packfile_packfile_proto_rawDescGZIP(), []int{2}
}

func (x *UploadSession) GetUploadId() string {
	if x != nil {
		return x.UploadId
	}
	return ""
}

func (x *UploadSession) GetPackfileId() string {
	if x != nil {
		return x.PackfileId
	}
	return ""
}

func (x *UploadSession) GetRepositoryId() string {
	if x != nil {
		return x.RepositoryId
	}
	return ""
}

func (x *UploadSession) GetTmpPath() string {
	if x != nil {
		return x.TmpPath
	}
	return ""
}

func (x *UploadSession) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *UploadSession) GetExpectedSize() int64 {
	if x != nil {
		return x.ExpectedSize
	}
	return 0
}

func (x *UploadSession) GetExpectedChecksum() string {
	if x != nil {
		return x.ExpectedChecksum
	}
	return ""
}

func (x *UploadSession) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *UploadSession) GetExpectedObjectCount() int64 {
	if x != nil {
		return x.ExpectedObjectCount
	}
	return 0
}

var File_packfile_packfile_proto protoreflect.FileDescriptor

const file_packfile_packfile_proto_rawDesc = "" +
	"\n" +
	"\x17packfile/packfile.proto\x12\bpackfile\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x04\n" +
	"\x10PackfileMetadata\x12\x1f\n" +
	"\vpackfile_id\x18\x01 \x01(\tR\n" +
	"packfileId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.packfile.PackfileStatusR\x06status\x12H\n" +
	"\x0eclassification\x18\x03 \x01(\x0e2 .packfile.PackfileClassificationR\x0eclassification\x12#\n" +
	"\rrepository_id\x18\x04 \x01(\tR\frepositoryId\x12+\n" +
	"\x11storage_namespace\x18\x05 \x01(\tR\x10storageNamespace\x12!\n" +
	"\fobject_count\x18\x06 \x01(\x03R\vobjectCount\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\a \x01(\x03R\tsizeBytes\x122\n" +
	"\x15size_bytes_compressed\x18\b \x01(\x03R\x13sizeBytesCompressed\x123\n" +
	"\x15compression_algorithm\x18\t \x01(\tR\x14compressionAlgorithm\x12-\n" +
	"\x12checksum_algorithm\x18\n" +
	" \x01(\tR\x11checksumAlgorithm\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12.\n" +
	"\x13source_packfile_ids\x18\f \x03(\tR\x11sourcePackfileIds\"\x99\x02\n" +
	"\x10PackfileSnapshot\x12#\n" +
	"\rrepository_id\x18\x01 \x01(\tR\frepositoryId\x12.\n" +
	"\x13active_packfile_ids\x18\x02 \x03(\tR\x11activePackfileIds\x12.\n" +
	"\x13staged_packfile_ids\x18\x03 \x03(\tR\x11stagedPackfileIds\x12@\n" +
	"\x0elast_commit_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\flastCommitAt\x12>\n" +
	"\rlast_merge_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vlastMergeAt\"\xf0\x02\n" +
	"\rUploadSession\x12\x1b\n" +
	"\tupload_id\x18\x01 \x01(\tR\buploadId\x12\x1f\n" +
	"\vpackfile_id\x18\x02 \x01(\tR\n" +
	"packfileId\x12#\n" +
	"\rrepository_id\x18\x03 \x01(\tR\frepositoryId\x12\x19\n" +
	"\btmp_path\x18\x04 \x01(\tR\atmpPath\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12#\n" +
	"\rexpected_size\x18\x06 \x01(\x03R\fexpectedSize\x12+\n" +
	"\x11expected_checksum\x18\a \x01(\tR\x10expectedChecksum\x12 \n" +
	"\vcompression\x18\b \x01(\tR\vcompression\x122\n" +
	"\x15expected_object_count\x18\t \x01(\x03R\x13expectedObjectCount*H\n" +
	"\x0ePackfileStatus\x12\n" +
	"\n" +
	"\x06STAGED\x10\x00\x12\r\n" +
	"\tCOMMITTED\x10\x01\x12\x0e\n" +
	"\n" +
	"SUPERSEDED\x10\x02\x12\v\n" +
	"\aDELETED\x10\x03*;\n" +
	"\x16PackfileClassification\x12\x10\n" +
	"\fSECOND_CLASS\x10\x00\x12\x0f\n" +
	"\vFIRST_CLASS\x10\x01B*Z(github.com/treeverse/lakefs/pkg/packfileb\x06proto3"

var (
	file_packfile_packfile_proto_rawDescOnce sync.Once
	file_packfile_packfile_proto_rawDescData []byte
)

func file_packfile_packfile_proto_rawDescGZIP() []byte {
	file_packfile_packfile_proto_rawDescOnce.Do(func() {
		file_packfile_packfile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packfile_packfile_proto_rawDesc), len(file_packfile_packfile_proto_rawDesc)))
	})
	return file_packfile_packfile_proto_rawDescData
}

var file_packfile_packfile_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_packfile_packfile_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_packfile_packfile_proto_goTypes = []any{
	(PackfileStatus)(0),           // 0: packfile.PackfileStatus
	(PackfileClassification)(0),   // 1: packfile.PackfileClassification
	(*PackfileMetadata)(nil),      // 2: packfile.PackfileMetadata
	(*PackfileSnapshot)(nil),      // 3: packfile.PackfileSnapshot
	(*UploadSession)(nil),         // 4: packfile.UploadSession
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_packfile_packfile_proto_depIdxs = []int32{
	0, // 0: packfile.PackfileMetadata.status:type_name -> packfile.PackfileStatus
	1, // 1: packfile.PackfileMetadata.classification:type_name -> packfile.PackfileClassification
	5, // 2: packfile.PackfileMetadata.created_at:type_name -> google.protobuf.Timestamp
	5, // 3: packfile.PackfileSnapshot.last_commit_at:type_name -> google.protobuf.Timestamp
	5, // 4: packfile.PackfileSnapshot.last_merge_at:type_name -> google.protobuf.Timestamp
	5, // 5: packfile.UploadSession.created_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_packfile_packfile_proto_init() }
func file_packfile_packfile_proto_init() {
	if File_packfile_packfile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packfile_packfile_proto_rawDesc), len(file_packfile_packfile_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packfile_packfile_proto_goTypes,
		DependencyIndexes: file_packfile_packfile_proto_depIdxs,
		EnumInfos:         file_packfile_packfile_proto_enumTypes,
		MessageInfos:      file_packfile_packfile_proto_msgTypes,
	}.Build()
	File_packfile_packfile_proto = out.File
	file_packfile_packfile_proto_goTypes = nil
	file_packfile_packfile_proto_depIdxs = nil
}
